[[pages]]
path = "/"
screenshotTimestamp = "2026-06-07T06:03:09Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/432cdb41-1df6-4dcf-94df-6680f5a89d72/f7e0fcaa-8e4c-4365-b094-58c68fe746a4/R4rwJC4"
